## Basic Configuration 
baseURL = "www.example.com"
defaultContentLanguage = "pt-br" #required if you are going to use more than one language
themesDir = "themes"
theme = "hyde-hyde"
author = "Author Name"
pluralizeListTitles = false

## Site Settings
[params]
    author = "Author Name"
    title = "Title"
    mainSections = "posts" 
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    copyright = "htr3n"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

relatedPosts = true

[languages]
  [languages.pt-br]
    description = "Descrição no idioma settado em defaultContentLanguage"
    languageName = "Português do Brasil"
    weight = 5
  [languages.en]
    description  = "Description text in the sidebar in English"
    languageName = "English"
    weight = 10 

[languages.pt-br.Menus]
      main = [
    { Name = "Posts", URL = "/", weight = 5 },
    { Name = "Sobre Mim", URL = "/about/", weight = 10 },
    { Name = "Versão em Inglês", URL = "/en", weight = 100 }
    ]


[languages.en.Menus]
      main = [
    { Name = "Posts", URL = "/en", weight = 5 },
    { Name = "About me", URL = "/en/about", weight = 10 },
    { Name = "Portuguese Version", URL = "/", weight = 100 }
  ]
